// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace HealthcareAppointment.Models.Models;

public partial class Appointment
{
    public string Id { get; set; }

    public string PatientId { get; set; }

    public string DoctorId { get; set; }

    public DateTime Date { get; set; }

    public int Status { get; set; }
    [NotMapped]
    public AppointmentStatus AppointmentStatus
    {
        get => (AppointmentStatus)Status;
        set => Status = (int)value;
    }

    public virtual User Doctor { get; set; }

    public virtual User Patient { get; set; }
}